mod args;

use chrono::prelude::*;
// Use clap for CLI argument parsing
use clap::Parser;
use colored::Colorize;
use csv::{ReaderBuilder, WriterBuilder};
// Use dateparser for chrono datetime parsing
use dateparser::{parse, parse_with};
use regex::Regex;
use std::{fs::{self, File, OpenOptions}, io};

use crate::args::{CalArgs, EventOptions};

/// Default time for calendar events set to 02:00:00.000...
// Hopefully no one will be awake adding to their calendar at that millisecond
const DEFAULT_TIME: NaiveTime = NaiveTime::from_hms_opt(1, 59, 59).unwrap();
// Default save file name
const FILE_NAME: &str = "events.csv";

// Object to be appended to CSV
#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct CalendarEvent {
    title: String,
    start_date: String,
    end_date: String,
    location: String,
    repeat: String,
    description: String
}

fn main() -> Result<(), String> {
    let cli = CalArgs::parse();
    // Switch case for each of the available CLI options
    match &cli.event {
        // ADD TO CALENDAR
        EventOptions::Add(args) => {
            // Parsing String into DateTimes
            let joined_dates: String = args.datetimes.join(" "); 
            let mut dates: Vec<DateTime<Local>> = Vec::new();
            let re: Regex = Regex::new(r"^(?:(.+[^\s])\s*,\s*(.+)|((.+[^,^\s])))$").unwrap();
            // I just learned how to declare variables in an if statement, is it obvious?
            if let Some(caps) = re.captures(&joined_dates) {
                for i in 1..=3 {
                    if let Some(m) = caps.get(i) && let Ok(d) = parse_with(m.as_str(), &Local, DEFAULT_TIME){
                        // Not sure why but it won't work unless I add the with_timezone()
                        dates.push(d.with_timezone(&Local));
                    }
                }
            }
            // End of parsing DateTimes
            // If no dates are found in CLI input, exit
            if dates.is_empty() {
                let err: String = format!("No date(s) found in string `{joined_dates}`");
                Err(err)
            } else {
                // Does the event end of the same day or on a different day?
                let mut end:DateTime<Local> = Local::now();
                // Different Day
                if dates.len() > 1 {
                    end = dates[1];
                // Same Day
                } else {
                    end = dates[0];
                }
                // If the end is earlier than the start, fix it
                // this 1 `if` expression generated by ChatGPT
                // ---------- Start of generated content
                if end < dates[0] {
                    let date = dates[0].date_naive();
                    let time = end.time();
                    end = Local.from_local_datetime(&(date.and_time(time)))
                        .earliest()
                        .expect("Invalid local datetime");
                }
                // ---------- End of generated content
                // Create calendar event to add to csv
                let e: CalendarEvent = CalendarEvent {
                    title: args.title.clone(),
                    start_date: dates[0].to_string(),
                    end_date: end.to_string(),
                    location: args.location.clone().unwrap_or("None".to_string()),
                    repeat: args.repeat.clone().unwrap_or("None".to_string()),
                    description: args.description.clone().unwrap_or("None".to_string())
                };
                // Print a bunch of info to confirm that the event is correct
                println!("=== Event Details ===\nTitle: {}", e.title.green());
                println!("Start Date: {}", e.start_date.green());
                println!("End Date: {}", e.end_date.green());
                println!("Location: {}", e.location.green());
                println!("Repeating: {}", e.repeat.green());
                println!("Description: {}", e.description.green());
                // I/O based on https://www.geeksforgeeks.org/rust/standard-i-o-in-rust/
                println!("Would you like to add this event to your calendar? Y/N");
                let mut response = String::new();
                io::stdin().read_line(&mut response).expect("Failed to readline");

                if response.to_lowercase() == "y\n" {
                    // If the file doesn't exist
                    if !fs::exists(FILE_NAME).unwrap() {
                        let mut file = File::create(FILE_NAME).unwrap();
                        // Big difference: Add a header to the csv
                        let mut wtr = WriterBuilder::new()
                            .has_headers(true)
                            .from_writer(file);
                        wtr.serialize(e);
                    // If the file exists
                    } else {
                        // Open file in APPEND mode to not overwrite
                        let file: File = OpenOptions::new().append(true).open(FILE_NAME).unwrap();
                        let mut wtr = WriterBuilder::new()
                            .has_headers(false)
                            .from_writer(file);
                        wtr.serialize(e);
                    }
                }
                // Everything worked!
                Ok(())
            } 
        },
        EventOptions::View(args) => {
            // Open file based on https://docs.rs/csv/latest/csv/struct.ReaderBuilder.html
            let mut rdr = ReaderBuilder::new().from_path(FILE_NAME).unwrap();
            let mut events: Vec<CalendarEvent> = Vec::new();
            for result in rdr.deserialize() {
                let event: CalendarEvent = result.unwrap();
                events.push(event);
            }
            // Sort Events By Date
            events.sort_by_key(|x: &CalendarEvent| x.start_date.clone());
            let today = Local::now();
            let mut prev_date = parse(&events.get(0).unwrap().start_date).unwrap().with_timezone(&Local);
            if args.all.unwrap() {
                println!("{}", prev_date.format("%m-%d-%Y").to_string().blue().bold());
            } else {
                println!("{}", today.format("%m-%d-%Y").to_string().blue().bold());
            }
            for event in &events {
                let current_date = parse(&event.start_date).unwrap().with_timezone(&Local);
                if args.all.unwrap() {
                    if prev_date.year() == current_date.year() && prev_date.month() == current_date.month() && prev_date.day() == current_date.day() {
                        // Pass
                    } else {
                        let print_date = current_date.format("%m-%d-%Y").to_string().blue().bold();
                        println!("\n{}", print_date);
                        prev_date = current_date;
                    }
                    print!("{}-{}: {}", 
                        current_date.format("%H:%M").to_string().purple(),
                        parse(&event.end_date).unwrap().with_timezone(&Local).format("%H:%M").to_string().purple(),
                        event.title);
                } else {
                    if today.year() == current_date.year() && today.month() == current_date.month() && today.day() == current_date.day() {
                        print!("{}-{}: {}", 
                        current_date.format("%H:%M").to_string().purple(),
                        parse(&event.end_date).unwrap().with_timezone(&Local).format("%H:%M").to_string().purple(),
                        event.title);
                    }
                }
                // Print these things only if they're selected
                if args.location.unwrap() {
                    if event.location != "None" {
                        print!(" ({})", event.location);
                    }
                }
                if args.repeat.unwrap() {
                    if event.repeat != "None" {
                        print!(", repeats {}", event.repeat);
                    }
                }
                if today.year() == current_date.year() && today.month() == current_date.month() && today.day() == current_date.day() {
                    print!("\n");
                } else if args.all.unwrap() {
                    print!("\n");
                }
                
            }
            Ok(())
        }
        _ => {Ok(())}
    }
}
